package PayrollManagementSystem;

/**
 *
 * @author yanniechiem
 */
public class PaySlipDetail extends javax.swing.JFrame {

    /**
     * Creates new form PaySlipDetail
     */
    public PaySlipDetail(String paySlip) {
        initComponents();
        jlblPaySlip.setText(paySlip);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jlblPaySlip = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jlblPaySlip.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jlblPaySlip.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblPaySlip.setToolTipText("");
        jScrollPane1.setViewportView(jlblPaySlip);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlblPaySlip;
    // End of variables declaration//GEN-END:variables
}
