package PayrollManagementSystem;

import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yanniechiem
 */
public class PaySlipGenerator extends javax.swing.JFrame {

    private static Employee emp;
    private static DefaultTableModel model;
    private static int selectedRow;

    /**
     * Creates new form PaySlip
     */
    public PaySlipGenerator(Employee emp) {
        initComponents();
        PaySlipGenerator.emp = emp;
        loadingPeriod(emp);
        jlblId.setText(emp.getId());
        jlblName.setText(emp.getName());
        jtxtLeaveRemain.setText(Integer.toString(emp.getLeavesRemain()));
        loadTable(emp);
        jbtnView.setVisible(false);
    }

    public void loadingPeriod(Employee emp) {
        int month, year;
        if (emp.getPaySlips().isEmpty()) {
            month = emp.getMonthEmployed();
            year = emp.getYearEmployed();
            jtxtPeriod.setText(month + " - " + Integer.toString(year));
        } else {
            month = emp.getMonthPaySlip();
            if (month == 12) {
                month = 1;
                year = emp.getYearPaySlip() + 1;
            } else {
                month += 1;
                year = emp.getYearPaySlip();
            }
            jtxtPeriod.setText(month + " - " + Integer.toString(year));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtxtLeaveTaken = new javax.swing.JTextField();
        jlblPeriod = new javax.swing.JLabel();
        jtxtLeaveRemain = new javax.swing.JTextField();
        jlblLeaveRemain = new javax.swing.JLabel();
        jlblLeaveTaken = new javax.swing.JLabel();
        jbtnGenerate = new javax.swing.JButton();
        jlblBonus = new javax.swing.JLabel();
        jtxtBonus = new javax.swing.JTextField();
        jlblDeduction = new javax.swing.JLabel();
        jtxtDeduction = new javax.swing.JTextField();
        jtxtPeriod = new javax.swing.JTextField();
        jbtnView = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jlblName = new javax.swing.JLabel();
        jlblEmployee2 = new javax.swing.JLabel();
        jlblId = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblPaySlips = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jtxtLeaveTaken.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtLeaveTaken.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtLeaveTakenKeyTyped(evt);
            }
        });

        jlblPeriod.setText("Period");
        jlblPeriod.setToolTipText("");
        jlblPeriod.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jtxtLeaveRemain.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtLeaveRemain.setEnabled(false);

        jlblLeaveRemain.setText("Leave remain");
        jlblLeaveRemain.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jlblLeaveTaken.setText("Leave taken");
        jlblLeaveTaken.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jbtnGenerate.setText("Generate Pay Slip");
        jbtnGenerate.setToolTipText("");
        jbtnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGenerateActionPerformed(evt);
            }
        });

        jlblBonus.setText("Bonus");
        jlblBonus.setToolTipText("");
        jlblBonus.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jtxtBonus.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtBonus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtBonusKeyTyped(evt);
            }
        });

        jlblDeduction.setText("Deduction");
        jlblDeduction.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jtxtDeduction.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtDeduction.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtDeductionKeyTyped(evt);
            }
        });

        jtxtPeriod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtPeriod.setEnabled(false);

        jbtnView.setText("View Pay Slip");
        jbtnView.setToolTipText("");
        jbtnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnView)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnGenerate))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlblBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtBonus))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlblLeaveRemain, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtLeaveRemain, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jlblPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtxtPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))
                            .addComponent(jlblDeduction, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtDeduction, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlblLeaveTaken)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxtLeaveTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtxtLeaveRemain, jtxtLeaveTaken});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlblLeaveTaken, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtLeaveTaken, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtDeduction, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblDeduction, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtxtLeaveRemain, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlblLeaveRemain, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtxtPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlblPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnGenerate)
                    .addComponent(jbtnView, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jtxtBonus, jtxtDeduction, jtxtLeaveRemain, jtxtLeaveTaken, jtxtPeriod});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbtnGenerate, jbtnView});

        jlblName.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jlblName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlblName.setText("Name");

        jlblEmployee2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jlblEmployee2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblEmployee2.setText("-");

        jlblId.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jlblId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblId.setText("ID");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblId, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblEmployee2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblName, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jlblId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblEmployee2)
                    .addComponent(jlblName))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jlblEmployee2, jlblId, jlblName});

        jtblPaySlips.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Period"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblPaySlips.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtblPaySlips.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblPaySlipsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtblPaySlips);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGenerateActionPerformed
        //Get period
        String month = jtxtPeriod.getText().length() == 8
                ? jtxtPeriod.getText().substring(0, 1)
                : jtxtPeriod.getText().substring(0, 2);
        emp.setMonthPaySlip(Integer.parseInt(month));

        String year = jtxtPeriod.getText().length() == 8
                ? jtxtPeriod.getText().substring(4, 8)
                : jtxtPeriod.getText().substring(5, 9);
        emp.setYearPaySlip(Integer.parseInt(year));

        //Update leaves
        emp.updateLeaves(Integer.parseInt(jtxtLeaveTaken.getText()
                .equals("") ? "0" : jtxtLeaveTaken.getText()));

        //Get bonus and deduction
        emp.setBonus(Double.parseDouble(jtxtBonus.getText()
                .equals("") ? "0" : jtxtBonus.getText()));
        emp.setAddDeduction(Double.parseDouble(jtxtDeduction.getText()
                .equals("") ? "0" : jtxtDeduction.getText()));

        emp.generatePaySlip();
        loadTable(emp);
    }//GEN-LAST:event_jbtnGenerateActionPerformed

    public void loadTable(Employee emp) {
        model = (DefaultTableModel) jtblPaySlips.getModel();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        for (int[] key : emp.getPaySlips().keySet()) {
            String row = Integer.toString(key[0]) + "-" + Integer.toString(key[1]);
            model.addRow(new Object[]{row, 0});
        }
    }

    private void jtxtLeaveTakenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtLeaveTakenKeyTyped
        char keyType = evt.getKeyChar();
        if (!(Character.isDigit(keyType) || (keyType == KeyEvent.VK_BACK_SPACE)
                || (keyType == KeyEvent.VK_DELETE))) {
            // If the character is not a digit, backspace, or delete, consume the event
            evt.consume();
        }
    }//GEN-LAST:event_jtxtLeaveTakenKeyTyped

    private void jtxtBonusKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBonusKeyTyped
        char keyType = evt.getKeyChar();
        if (!(Character.isDigit(keyType) || (keyType == KeyEvent.VK_BACK_SPACE)
                || (keyType == KeyEvent.VK_DELETE))) {
            // If the character is not a digit, backspace, or delete, consume the event
            evt.consume();
        }
    }//GEN-LAST:event_jtxtBonusKeyTyped

    private void jtxtDeductionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDeductionKeyTyped
        char keyType = evt.getKeyChar();
        if (!(Character.isDigit(keyType) || (keyType == KeyEvent.VK_BACK_SPACE)
                || (keyType == KeyEvent.VK_DELETE))) {
            // If the character is not a digit, backspace, or delete, consume the event
            evt.consume();
        }
    }//GEN-LAST:event_jtxtDeductionKeyTyped

    private void jbtnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnViewActionPerformed
        String period = model.getValueAt(selectedRow, 0).toString();
        String month = period.length() == 6
                ? period.substring(0, 1)
                : period.substring(0, 2);

        String year = period.length() == 6
                ? period.substring(2, 6)
                : period.substring(3, 7);

        int[] key = {Integer.parseInt(month), Integer.parseInt(year)};
        
        String pl = emp.getPaySlipDetail(key);
        
        PaySlipDetail detail = new PaySlipDetail(emp.getPaySlipDetail(key));
        detail.setVisible(true);
    }//GEN-LAST:event_jbtnViewActionPerformed

    private void jtblPaySlipsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblPaySlipsMouseClicked
        model = (DefaultTableModel) jtblPaySlips.getModel();
        selectedRow = jtblPaySlips.getSelectedRow();
        jbtnView.setVisible(true);
    }//GEN-LAST:event_jtblPaySlipsMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnGenerate;
    private javax.swing.JButton jbtnView;
    private javax.swing.JLabel jlblBonus;
    private javax.swing.JLabel jlblDeduction;
    private javax.swing.JLabel jlblEmployee2;
    private javax.swing.JLabel jlblId;
    private javax.swing.JLabel jlblLeaveRemain;
    private javax.swing.JLabel jlblLeaveTaken;
    private javax.swing.JLabel jlblName;
    private javax.swing.JLabel jlblPeriod;
    private javax.swing.JTable jtblPaySlips;
    private javax.swing.JTextField jtxtBonus;
    private javax.swing.JTextField jtxtDeduction;
    private javax.swing.JTextField jtxtLeaveRemain;
    private javax.swing.JTextField jtxtLeaveTaken;
    private javax.swing.JTextField jtxtPeriod;
    // End of variables declaration//GEN-END:variables
}
